name: fluttercommerce
description: Shopping UI design in Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  country_pickers: ^1.1.0
  flutter_icons: ^0.2.5
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  division: ^0.6.1
  page_transition: '^1.1.0'
  bottom_navy_bar: ^5.1.0
  sliding_up_panel: ^0.3.4
  flutter_xlider: ^2.5.1
  intro_views_flutter: ^2.6.0
  rflutter_alert: ^1.0.3
  hidden_drawer_menu: ^1.1.2
  bloc: ^6.1.0
  equatable: ^1.2.3
  flutter_bloc: ^6.1.0
  formz: ^0.3.0
  google_fonts: ^1.1.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  http: ^0.12.0+4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.5
  rxdart: ^0.24.0
  flutter_html: ^0.8.2
  intl: ^0.16.1
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.8.2
  build_runner: ^1.10.11

flutter_launcher_name:
  name: "Bach's Shop"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  # - assets/Spinner.gif

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf
